'use client';

import { useState } from 'react';
import { SiteLayout } from '@/components/layout/site-layout';
import { SchemaMarkup } from '@/components/schema-markup';
import { useCapRateCalculator } from '@/hooks/useCapRateCalculator';

const FEATURES = [
  {
    title: 'Cap Rate Calculation',
    description: 'Calculate the capitalization rate by entering the Net Operating Income (NOI) and property value to evaluate investment returns.',
  },
  {
    title: 'Reverse Calculation',
    description: 'Determine property value from a target cap rate and NOI to understand what you should pay for an investment property.',
  },
  {
    title: 'Risk Assessment',
    description: 'Get instant interpretation of your cap rate with risk level indicators to help make informed investment decisions.',
  },
];

const FAQS = [
  {
    question: 'What is cap rate in real estate?',
    answer: 'Cap rate (capitalization rate) is a real estate valuation metric that measures the rate of return on an investment property. It is calculated by dividing the Net Operating Income (NOI) by the property value.',
  },
  {
    question: 'How do you calculate cap rate?',
    answer: 'Cap Rate = (Net Operating Income / Property Value) x 100. For example, if a property generates $50,000 NOI annually and is worth $1,000,000, the cap rate is 5%.',
  },
  {
    question: 'What is a good cap rate?',
    answer: 'A "good" cap rate depends on the market, property type, and your investment goals. Generally, 4-6% is considered low risk in prime markets, 6-8% is moderate, and above 8% may indicate higher risk or value-add opportunities.',
  },
  {
    question: 'What is Net Operating Income (NOI)?',
    answer: 'NOI is the annual income generated by a property after deducting operating expenses like property taxes, insurance, maintenance, and management fees, but before mortgage payments and income taxes.',
  },
  {
    question: 'Why do higher cap rates mean more risk?',
    answer: 'Higher cap rates often indicate higher perceived risk due to factors like location, property condition, tenant quality, or market volatility. Investors demand higher returns to compensate for increased uncertainty.',
  },
  {
    question: 'Can cap rate be used to determine property value?',
    answer: 'Yes, by rearranging the formula: Property Value = NOI / Cap Rate. If you know the market cap rate for similar properties and your NOI, you can estimate what your property should be worth.',
  },
];

export function CapRateCalculator() {
  const { result, calculate, reset } = useCapRateCalculator();

  const [mode, setMode] = useState<'capRate' | 'propertyValue'>('capRate');
  const [noi, setNoi] = useState('');
  const [propertyValue, setPropertyValue] = useState('');
  const [capRate, setCapRate] = useState('');

  const handleCalculate = () => {
    const noiValue = parseFloat(noi);
    if (!noiValue || noiValue <= 0) return;

    if (mode === 'capRate') {
      const propValue = parseFloat(propertyValue);
      if (!propValue || propValue <= 0) return;
      calculate({ mode, noi: noiValue, propertyValue: propValue });
    } else {
      const capRateValue = parseFloat(capRate);
      if (!capRateValue || capRateValue <= 0) return;
      calculate({ mode, noi: noiValue, capRate: capRateValue });
    }
  };

  const handleReset = () => {
    reset();
    setNoi('');
    setPropertyValue('');
    setCapRate('');
  };

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(amount);
  };

  const getRiskColor = (riskLevel: 'low' | 'moderate' | 'high') => {
    switch (riskLevel) {
      case 'low':
        return 'text-green-600';
      case 'moderate':
        return 'text-yellow-600';
      case 'high':
        return 'text-red-600';
    }
  };

  const softwareSchema = {
    '@context': 'https://schema.org',
    '@type': 'SoftwareApplication',
    name: 'Cap Rate Calculator',
    description: 'Calculate real estate capitalization rate (cap rate) and property value from NOI for investment analysis.',
    applicationCategory: 'FinanceApplication',
    operatingSystem: 'Web',
    offers: {
      '@type': 'Offer',
      price: '0',
      priceCurrency: 'USD',
    },
  };

  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: FAQS.map((faq) => ({
      '@type': 'Question',
      name: faq.question,
      acceptedAnswer: {
        '@type': 'Answer',
        text: faq.answer,
      },
    })),
  };

  return (
    <SiteLayout toolName="Cap Rate Calculator" category="real-estate-tools">
      <SchemaMarkup schema={softwareSchema} />
      <SchemaMarkup schema={faqSchema} />

      <div className="max-w-4xl mx-auto">
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-6 mb-8">
          <h2 className="text-2xl font-bold mb-6 text-gray-900 dark:text-white">
            Calculate Cap Rate
          </h2>

          {/* Mode Selection */}
          <div className="mb-6">
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Calculation Mode
            </label>
            <div className="flex gap-4">
              <label className="flex items-center">
                <input
                  type="radio"
                  name="mode"
                  value="capRate"
                  checked={mode === 'capRate'}
                  onChange={() => setMode('capRate')}
                  className="mr-2"
                />
                <span className="text-gray-700 dark:text-gray-300">Calculate Cap Rate</span>
              </label>
              <label className="flex items-center">
                <input
                  type="radio"
                  name="mode"
                  value="propertyValue"
                  checked={mode === 'propertyValue'}
                  onChange={() => setMode('propertyValue')}
                  className="mr-2"
                />
                <span className="text-gray-700 dark:text-gray-300">Calculate Property Value</span>
              </label>
            </div>
          </div>

          {/* Input Fields */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                Annual Net Operating Income (NOI) ($)
              </label>
              <input
                type="number"
                value={noi}
                onChange={(e) => setNoi(e.target.value)}
                placeholder="50000"
                className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
              />
            </div>
            {mode === 'capRate' ? (
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Property Value ($)
                </label>
                <input
                  type="number"
                  value={propertyValue}
                  onChange={(e) => setPropertyValue(e.target.value)}
                  placeholder="1000000"
                  className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                />
              </div>
            ) : (
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Target Cap Rate (%)
                </label>
                <input
                  type="number"
                  step="0.1"
                  value={capRate}
                  onChange={(e) => setCapRate(e.target.value)}
                  placeholder="6"
                  className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                />
              </div>
            )}
          </div>

          {/* Action Buttons */}
          <div className="flex gap-4">
            <button
              onClick={handleCalculate}
              className="px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white font-medium rounded-lg transition-colors"
            >
              Calculate
            </button>
            <button
              onClick={handleReset}
              className="px-6 py-3 bg-gray-200 dark:bg-gray-700 hover:bg-gray-300 dark:hover:bg-gray-600 text-gray-700 dark:text-gray-300 font-medium rounded-lg transition-colors"
            >
              Reset
            </button>
          </div>
        </div>

        {/* Results */}
        {result && (
          <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-6 mb-8">
            <h3 className="text-xl font-bold mb-4 text-gray-900 dark:text-white">
              Results
            </h3>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
              <div className="p-4 bg-blue-100 dark:bg-blue-900/30 rounded-lg">
                <div className="text-sm text-blue-600 dark:text-blue-400">Cap Rate</div>
                <div className="text-2xl font-bold text-gray-900 dark:text-white">
                  {result.capRate.toFixed(2)}%
                </div>
              </div>
              <div className="p-4 bg-gray-100 dark:bg-gray-700 rounded-lg">
                <div className="text-sm text-gray-600 dark:text-gray-400">Property Value</div>
                <div className="text-2xl font-bold text-gray-900 dark:text-white">
                  {formatCurrency(result.propertyValue)}
                </div>
              </div>
              <div className="p-4 bg-gray-100 dark:bg-gray-700 rounded-lg">
                <div className="text-sm text-gray-600 dark:text-gray-400">Annual NOI</div>
                <div className="text-2xl font-bold text-gray-900 dark:text-white">
                  {formatCurrency(result.noi)}
                </div>
              </div>
            </div>

            <div className="p-4 bg-gray-50 dark:bg-gray-700/50 rounded-lg">
              <div className="flex items-center gap-2 mb-2">
                <span className="text-sm font-medium text-gray-700 dark:text-gray-300">Risk Level:</span>
                <span className={`font-bold capitalize ${getRiskColor(result.riskLevel)}`}>
                  {result.riskLevel}
                </span>
              </div>
              <p className="text-gray-600 dark:text-gray-400">{result.interpretation}</p>
            </div>
          </div>
        )}

        {/* Feature Cards */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
          {FEATURES.map((feature, index) => (
            <div
              key={index}
              className="bg-white dark:bg-gray-800 rounded-lg shadow p-6"
            >
              <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">
                {feature.title}
              </h3>
              <p className="text-gray-600 dark:text-gray-400">{feature.description}</p>
            </div>
          ))}
        </div>

        {/* FAQs */}
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-6">
          <h2 className="text-2xl font-bold mb-6 text-gray-900 dark:text-white">
            Frequently Asked Questions
          </h2>
          <div className="space-y-4">
            {FAQS.map((faq, index) => (
              <div
                key={index}
                className="border-b border-gray-200 dark:border-gray-700 pb-4 last:border-0"
              >
                <h3 className="font-semibold text-gray-900 dark:text-white mb-2">
                  {faq.question}
                </h3>
                <p className="text-gray-600 dark:text-gray-400">{faq.answer}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </SiteLayout>
  );
}
