'use client';

import React, { useEffect } from 'react';
import SiteLayout from '@/components/layout/site-layout';
import SchemaMarkup from '@/components/schema-markup';
import { useMarketShareCalculator } from '@/hooks/useMarketShareCalculator';
import { PlusCircle, Trash2, PieChart, TrendingUp, Users } from 'lucide-react';

const FAQS = [
  {
    question: 'What is market share?',
    answer: 'Market share is the percentage of total sales in an industry generated by a particular company. It is calculated by dividing the company\'s revenue by the total market size and multiplying by 100.',
  },
  {
    question: 'How do I calculate market share percentage?',
    answer: 'Market share percentage = (Company Revenue / Total Market Size) x 100. For example, if your company has $10 million in revenue and the total market is $100 million, your market share is 10%.',
  },
  {
    question: 'Why is market share important?',
    answer: 'Market share indicates a company\'s competitiveness and market position. Higher market share often means greater influence, economies of scale, and stronger bargaining power with suppliers.',
  },
  {
    question: 'What is a good market share percentage?',
    answer: 'A "good" market share varies by industry. In highly fragmented markets, 10-15% might be considered strong. In concentrated markets, leaders may hold 30-50% or more.',
  },
  {
    question: 'How can I increase my market share?',
    answer: 'Strategies include competitive pricing, product differentiation, expanding distribution channels, increasing marketing efforts, acquiring competitors, or entering new market segments.',
  },
  {
    question: 'What is the difference between market share and market size?',
    answer: 'Market size is the total revenue or volume of sales in an entire market or industry. Market share is the portion of that total captured by a specific company, expressed as a percentage.',
  },
];

const FEATURES = [
  {
    icon: PieChart,
    title: 'Visual Analysis',
    description: 'Interactive pie chart visualization shows market share distribution at a glance.',
  },
  {
    icon: Users,
    title: 'Competitor Comparison',
    description: 'Compare multiple competitors side-by-side to understand market dynamics.',
  },
  {
    icon: TrendingUp,
    title: 'Instant Calculations',
    description: 'Real-time percentage calculations as you enter revenue data.',
  },
];

export default function MarketShareCalculatorComponent() {
  const {
    competitors,
    totalMarketSize,
    results,
    addCompetitor,
    removeCompetitor,
    updateCompetitor,
    setTotalMarketSize,
    calculateMarketShares,
    reset,
  } = useMarketShareCalculator();

  useEffect(() => {
    calculateMarketShares();
  }, [competitors, totalMarketSize, calculateMarketShares]);

  const softwareSchema = {
    '@context': 'https://schema.org',
    '@type': 'SoftwareApplication',
    name: 'Market Share Calculator',
    description: 'Free online market share calculator. Calculate market share percentages and compare competitors with visual pie chart analysis.',
    url: 'https://conveniencepro.com/tools/market-share-calculator',
    applicationCategory: 'BusinessApplication',
    operatingSystem: 'Any',
    offers: {
      '@type': 'Offer',
      price: '0',
      priceCurrency: 'USD',
    },
  };

  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: FAQS.map((faq) => ({
      '@type': 'Question',
      name: faq.question,
      acceptedAnswer: {
        '@type': 'Answer',
        text: faq.answer,
      },
    })),
  };

  return (
    <SiteLayout toolName="Market Share Calculator" category="business-tools">
      <SchemaMarkup schema={softwareSchema} />
      <SchemaMarkup schema={faqSchema} />

      <div className="max-w-6xl mx-auto px-4 py-8">
        <div className="text-center mb-8">
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-2">
            Market Share Calculator
          </h1>
          <p className="text-gray-600 dark:text-gray-400">
            Calculate and visualize market share percentages for multiple competitors
          </p>
        </div>

        <div className="grid lg:grid-cols-2 gap-8 mb-12">
          {/* Input Section */}
          <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg p-6">
            <h2 className="text-xl font-semibold mb-4 text-gray-900 dark:text-white">
              Enter Data
            </h2>

            <div className="mb-6">
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                Total Market Size ($)
              </label>
              <input
                type="number"
                value={totalMarketSize || ''}
                onChange={(e) => setTotalMarketSize(Number(e.target.value))}
                placeholder="Enter total market size"
                className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 dark:bg-gray-700 dark:text-white"
              />
            </div>

            <div className="space-y-4">
              <div className="flex justify-between items-center">
                <h3 className="font-medium text-gray-900 dark:text-white">Competitors</h3>
                <button
                  onClick={addCompetitor}
                  className="flex items-center gap-1 text-blue-600 hover:text-blue-700 text-sm"
                >
                  <PlusCircle size={16} /> Add Competitor
                </button>
              </div>

              {competitors.map((competitor) => (
                <div key={competitor.id} className="flex gap-2 items-center">
                  <input
                    type="text"
                    value={competitor.name}
                    onChange={(e) => updateCompetitor(competitor.id, 'name', e.target.value)}
                    placeholder="Company name"
                    className="flex-1 px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg dark:bg-gray-700 dark:text-white text-sm"
                  />
                  <input
                    type="number"
                    value={competitor.revenue || ''}
                    onChange={(e) => updateCompetitor(competitor.id, 'revenue', Number(e.target.value))}
                    placeholder="Revenue ($)"
                    className="flex-1 px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg dark:bg-gray-700 dark:text-white text-sm"
                  />
                  {competitors.length > 2 && (
                    <button
                      onClick={() => removeCompetitor(competitor.id)}
                      className="p-2 text-red-500 hover:text-red-600"
                    >
                      <Trash2 size={16} />
                    </button>
                  )}
                </div>
              ))}
            </div>

            <button
              onClick={reset}
              className="mt-6 w-full py-2 bg-gray-200 dark:bg-gray-700 text-gray-700 dark:text-gray-300 rounded-lg hover:bg-gray-300 dark:hover:bg-gray-600 transition"
            >
              Reset
            </button>
          </div>

          {/* Results Section */}
          <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg p-6">
            <h2 className="text-xl font-semibold mb-4 text-gray-900 dark:text-white">
              Market Share Results
            </h2>

            {results.length > 0 ? (
              <>
                {/* Pie Chart */}
                <div className="flex justify-center mb-6">
                  <svg viewBox="0 0 200 200" className="w-48 h-48">
                    {(() => {
                      let cumulativePercent = 0;
                      return results.map((result) => {
                        const startPercent = cumulativePercent;
                        cumulativePercent += result.marketShare;
                        const startAngle = (startPercent / 100) * 360;
                        const endAngle = (cumulativePercent / 100) * 360;
                        const largeArcFlag = result.marketShare > 50 ? 1 : 0;
                        const startX = 100 + 80 * Math.cos((Math.PI * (startAngle - 90)) / 180);
                        const startY = 100 + 80 * Math.sin((Math.PI * (startAngle - 90)) / 180);
                        const endX = 100 + 80 * Math.cos((Math.PI * (endAngle - 90)) / 180);
                        const endY = 100 + 80 * Math.sin((Math.PI * (endAngle - 90)) / 180);

                        if (result.marketShare === 100) {
                          return (
                            <circle
                              key={result.id}
                              cx="100"
                              cy="100"
                              r="80"
                              fill={result.color}
                            />
                          );
                        }

                        if (result.marketShare === 0) return null;

                        return (
                          <path
                            key={result.id}
                            d={`M 100 100 L ${startX} ${startY} A 80 80 0 ${largeArcFlag} 1 ${endX} ${endY} Z`}
                            fill={result.color}
                          />
                        );
                      });
                    })()}
                  </svg>
                </div>

                {/* Legend */}
                <div className="space-y-2">
                  {results.map((result) => (
                    <div key={result.id} className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <div
                          className="w-4 h-4 rounded"
                          style={{ backgroundColor: result.color }}
                        />
                        <span className="text-gray-700 dark:text-gray-300">{result.name}</span>
                      </div>
                      <div className="text-right">
                        <span className="font-semibold text-gray-900 dark:text-white">
                          {result.marketShare.toFixed(2)}%
                        </span>
                        <span className="text-gray-500 dark:text-gray-400 text-sm ml-2">
                          (${result.revenue.toLocaleString()})
                        </span>
                      </div>
                    </div>
                  ))}
                </div>
              </>
            ) : (
              <div className="text-center text-gray-500 dark:text-gray-400 py-12">
                Enter market size and competitor revenues to see results
              </div>
            )}
          </div>
        </div>

        {/* Features */}
        <div className="mb-12">
          <h2 className="text-2xl font-bold text-center mb-8 text-gray-900 dark:text-white">
            Features
          </h2>
          <div className="grid md:grid-cols-3 gap-6">
            {FEATURES.map((feature, index) => (
              <div
                key={index}
                className="bg-white dark:bg-gray-800 rounded-xl shadow-lg p-6 text-center"
              >
                <feature.icon className="w-12 h-12 mx-auto mb-4 text-blue-600" />
                <h3 className="text-lg font-semibold mb-2 text-gray-900 dark:text-white">
                  {feature.title}
                </h3>
                <p className="text-gray-600 dark:text-gray-400">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>

        {/* FAQs */}
        <div>
          <h2 className="text-2xl font-bold text-center mb-8 text-gray-900 dark:text-white">
            Frequently Asked Questions
          </h2>
          <div className="grid md:grid-cols-2 gap-6">
            {FAQS.map((faq, index) => (
              <div
                key={index}
                className="bg-white dark:bg-gray-800 rounded-xl shadow-lg p-6"
              >
                <h3 className="font-semibold mb-2 text-gray-900 dark:text-white">
                  {faq.question}
                </h3>
                <p className="text-gray-600 dark:text-gray-400">{faq.answer}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </SiteLayout>
  );
}
